name: Generate Bomberman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # 12 மணி நேரத்திற்கு ஒருமுறை தானாக புதுப்பிக்கப்படும்
  workflow_dispatch: # Manual-ஆக ரன் பண்ணவும் உதவும்
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Bomberman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: bomberman # 👈 இங்கே 'bomberman' தீம் செட் செய்யப்பட்டுள்ளது

      - name: Push SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}