name: Generate Bomberman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # 12 மணி நேரத்திற்கு ஒருமுறை ரன் ஆகும்
  workflow_dispatch: # Manual-ஆக ரன் பண்ண
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Bomberman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          game: bomberman      # 💣 இங்கே 'bomberman' என மாற்றப்பட்டுள்ளது
          gameTheme: github-dark # Dark theme-க்காக

      - name: Push Bomberman SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}