name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Custom Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # கலர்களை இங்கு மாற்றிக்கொள்ளலாம்:
          color_snake: '#ff4d6d'        # Pac-man/Snake போகிற பாதை அல்லது ஹைலைட் கலர்
          color_dots: '#ff758f'         # சாப்பிடக்கூடிய dots (points) கலர்
          color_bg: '#161922'           # SVG-ன் Background கலர் (Dark PCB look)
          color_lines: 'rgba(255, 77, 109, 0.2)' # கட்டங்களுக்கு இடையே உள்ள கோடுகளின் (lines) கலர்

      - name: Push SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}